# Generated by Django 3.2.6 on 2021-08-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_no',
        ),
    ]
