# Generated by Django 3.2.6 on 2021-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210830_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
