# Generated by Django 3.2.6 on 2021-08-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210830_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_date',
        ),
    ]
