# Generated by Django 3.2.6 on 2021-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
